require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkoutTypesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkoutType. As you add validations to WorkoutType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all workout_types as @workout_types" do
      workout_type = WorkoutType.create! valid_attributes
      get :index
      assigns(:workout_types).should eq([workout_type])
    end
  end

  describe "GET show" do
    it "assigns the requested workout_type as @workout_type" do
      workout_type = WorkoutType.create! valid_attributes
      get :show, :id => workout_type.id
      assigns(:workout_type).should eq(workout_type)
    end
  end

  describe "GET new" do
    it "assigns a new workout_type as @workout_type" do
      get :new
      assigns(:workout_type).should be_a_new(WorkoutType)
    end
  end

  describe "GET edit" do
    it "assigns the requested workout_type as @workout_type" do
      workout_type = WorkoutType.create! valid_attributes
      get :edit, :id => workout_type.id
      assigns(:workout_type).should eq(workout_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkoutType" do
        expect {
          post :create, :workout_type => valid_attributes
        }.to change(WorkoutType, :count).by(1)
      end

      it "assigns a newly created workout_type as @workout_type" do
        post :create, :workout_type => valid_attributes
        assigns(:workout_type).should be_a(WorkoutType)
        assigns(:workout_type).should be_persisted
      end

      it "redirects to the created workout_type" do
        post :create, :workout_type => valid_attributes
        response.should redirect_to(WorkoutType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workout_type as @workout_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutType.any_instance.stub(:save).and_return(false)
        post :create, :workout_type => {}
        assigns(:workout_type).should be_a_new(WorkoutType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutType.any_instance.stub(:save).and_return(false)
        post :create, :workout_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workout_type" do
        workout_type = WorkoutType.create! valid_attributes
        # Assuming there are no other workout_types in the database, this
        # specifies that the WorkoutType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkoutType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => workout_type.id, :workout_type => {'these' => 'params'}
      end

      it "assigns the requested workout_type as @workout_type" do
        workout_type = WorkoutType.create! valid_attributes
        put :update, :id => workout_type.id, :workout_type => valid_attributes
        assigns(:workout_type).should eq(workout_type)
      end

      it "redirects to the workout_type" do
        workout_type = WorkoutType.create! valid_attributes
        put :update, :id => workout_type.id, :workout_type => valid_attributes
        response.should redirect_to(workout_type)
      end
    end

    describe "with invalid params" do
      it "assigns the workout_type as @workout_type" do
        workout_type = WorkoutType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutType.any_instance.stub(:save).and_return(false)
        put :update, :id => workout_type.id, :workout_type => {}
        assigns(:workout_type).should eq(workout_type)
      end

      it "re-renders the 'edit' template" do
        workout_type = WorkoutType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkoutType.any_instance.stub(:save).and_return(false)
        put :update, :id => workout_type.id, :workout_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workout_type" do
      workout_type = WorkoutType.create! valid_attributes
      expect {
        delete :destroy, :id => workout_type.id
      }.to change(WorkoutType, :count).by(-1)
    end

    it "redirects to the workout_types list" do
      workout_type = WorkoutType.create! valid_attributes
      delete :destroy, :id => workout_type.id
      response.should redirect_to(workout_types_url)
    end
  end

end
